# => experiment options
DEBUG: True
brute_force: True
EXP_NAME: '6P, 75deg28mm, F/2.0, 7.66mm sensor, lens design'
seed: 1

# Modify the following parameters if you want to design you own lens
# ==================
# Design spec
HFOV: 0.655 #46 50mm # half diagonal FoV in radian，cannot be too small
FNUM: 2.0 # F-number
DIAG: 7.66  # sensor diagonal length in mm
element: 6  # lens element number
# ==================

curriculum_steps: 5 # number of intermediate steps
FNUM_START: 2.8
DIAG_START: 4

# Learning rate
lrs: [5e-4, 1e-4, 1e-1, 1e-4]
ai_lr_decay: 0.1

# Random initialization
ai_degree: 6
flange: 1.2
rff: 0.9
d_aper: 0.1

# 去仿真小米等效75mm，视角30°的镜头，勇的imx858，f/1.8
# 可以仿照徕卡真实75mm的镜头https://www.leica-camera.cn/Photography/Leica-SL/SL-Lenses/Prime-Lenses/Apo-Summicron-SL_75_f/2_ASPH.html